### ISSUE TITLE
Cannot connect to "0.0.0.0:8080" after running "lc-serve deploy local api" 

### ISSUE THREAD

**Issue by jfdesgagne** [bhaskatripathi/pdfGPT#48] opened 2023-05-04 16:32 UTC
I have issues with the local playground. When I deploy langchain-serve locally, it seems to work, it says "Flow is ready to serve!" on "0.0.0.0:8080", but when I tried to access one of the listed endpoints from the browser it says that "This site can’t be reached".

**Comment by bhaskatripathi** [comment] 2023-05-04 18:25
@deepankarm - Please advise

**Comment by deepankarm** [comment] 2023-05-04 18:48
@jfdesgagne Can you please share the output of `jina -vf` command?

**Comment by jfdesgagne** [comment] 2023-05-04 19:06
@deepankarm thanks for the quick answer. Here's the console output

```shell
% jina -vf
- jina 3.15.0
- docarray 0.21.0
- jcloud 0.2.6
- jina-hubble-sdk 0.36.0
- jina-proto 0.1.17
- protobuf 3.19.6
- proto-backend python
- grpcio 1.47.5
- pyyaml 6.0
- python 3.10.8
- platform Darwin
- platform-release 21.1.0
- platform-version Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 266187455140091
- session-id 3dd3255a-eaae-11ed-8b79-f21898b510fb
- uptime 2023-05-04T12:02:39.541808
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
* JINA_STREAMER_ARGS (unset)
```

Also, here's the output from running `lc-serve deploy local api`

```shell
% lc-serve deploy local api
2023-05-04 12:04:44.700038: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO   gateway/rep-0@44877 Registering HTTP route: ask_file                                                                                                                                                                [05/04/23 12:04:51]
INFO   gateway/rep-0@44877 Registering HTTP route: ask_url
objc[44877]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[44877]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
───────────────────────────────────────────────────────────────────────────────────────────────────────── 🎉 Flow is ready to serve! ─────────────────────────────────────────────────────────────────────────────────────────────────────────
╭────────────── 🔗 Endpoint ───────────────╮
│  ⛓      Protocol                   HTTP  │
│  🏠        Local           0.0.0.0:8080  │
│  🔒      Private     192.168.4.233:8080  │
╰──────────────────────────────────────────╯
╭─────────── 💎 HTTP extension ────────────╮
│  💬          Swagger UI        .../docs  │
│  📚               Redoc       .../redoc  │
╰──────────────────────────────────────────╯
Do you love open source? Help us improve Jina in just 1 minute and 30 seconds by taking our survey: https://10sw1tcpld4.typeform.com/jinasurveyfeb23?utm_source=jina(Set environment variable JINA_HIDE_SURVEY=1 to hide this message.)
```

**Comment by deepankarm** [comment] 2023-05-04 19:11
Can you please set environment variable `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` on your terminal and retry?

**Comment by jfdesgagne** [comment] 2023-05-04 19:12
@deepankarm this did the tricks, thank you :) Any context about what is this SAFETY var for?

**Comment by deepankarm** [comment] 2023-05-04 19:16
It's a default setting in the new MacOS for multiprocessing. You can read more about it [here](https://docs.jina.ai/concepts/orchestration/troubleshooting-on-multiprocess/#using-multiprocessing-fork-on-macos). 

I'll add this to langchain-serve's FAQ. Please close the issue, if the issue is now resolved.

**Closed** 2023-05-04 19:17 UTC
